#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/demo_db
#    username: user
#    password: pass
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
spring:
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true

server:
  port: 8189
